### PR TITLE
lock package versions

### PR DESCRIPTION
**Pull request by walmartparkinglot**
image

### CODE REVIEW

**Comment by frozenpandaman** [comment]
I don't think this is needed and the project is too old for this type of change, sorry. (And I don't understand your image…)

**Comment by walmartparkinglot** [comment]
pray there are no breaking changes in future versioms then


image unrelated; github shitposting

**Comment by frozenpandaman** [comment]
I'll fix it at that time if there are breaking changes. :) I plan to support s2s until the end of Splatoon 2's lifetime.

**Comment by walmartparkinglot** [comment]
That's great to hear, I was under the impression this was a legacy project. I apologize if the last message came off as snarky, it was like 3am lol

**Comment by frozenpandaman** [comment]
No, you're good! The repo isn't updated much anymore cuz the game's not receiving any further updates, and most people are off playing Splatoon 3 anyway, but I do aim to keep s2s working (i.e. keeping the NSO headers up to date and cookie generation working). :)

**Pull request closed without merging**
