### PR TITLE
To merge with main

### PR DESCRIPTION
**Pull request by radsutton**
Hi Panda,

Command args have been merged into one.
DBS has been restored and replaced with a new Dict file, which also removes German hard coding.

This feature has been very useful for our long active squad, we copy it into an Excel table which better displays sessions and calculates further meaningful stats. I imagine it shall be useful for others, as development of the CSV export in stat.ink seems to have stalled. Furthermore, this feature is more convenient for large teams like ours.

Though the game is old, there is a second wave of competitive players and renewed interest in tournaments from lower level teams, at least in Europe.

Please review the code and comment any issues you find. This has been in two months of development now (with testing from my team).

### CODE REVIEW

**Comment by ofiala-a51** [comment]
I cannot help but wonder why you didn't go for .ods instead, considering it is an ISO standard (ISO/IEC 26300) and software for it is available on all major platforms free of charge. This would be much more useful than using a proprietary format which requires closed source, paid software which is unavailable for most platforms. This feature is completely useless to everyone except Microsoft Windows users. I am not a maintainer of this project, so this is just my opinion, but I think forking splatnet2statink into a separate project would make more sense than trying to push such a huge update that will benefit only a small subset of users.

**Comment by radsutton** [comment]
.xlsx was an excel standard and, like doc and docx, is now an open standard fully supported by many free to use programs. I personally use libreoffice. This format is supported by the python module and by the default standard spreadsheet program Excel.
This feature has been often asked for in stat.ink and exists nowhere else. There are plenty of Splatoon users and those who are interested in this program are likely also interested in a stat export for other purposes. Furthermore, there are users like my team who don't need stat.ink but still use stats.
-------- Original message --------From: ofiala-a51 <notifications@github.com> Date: 19/10/2020  20:01  (GMT+01:00) To: frozenpandaman/splatnet2statink <splatnet2statink@noreply.github.com> Cc: Richard Sutton <radsutton@hotmail.co.uk>, Author <author@noreply.github.com> Subject: Re: [frozenpandaman/splatnet2statink] To merge with main (#110) 
I cannot help but wonder why you didn't go for .ods instead, considering it is an ISO standard (ISO/IEC 26300) and software for it is available on all major platforms free of charge. This would be much more useful than using a proprietary format which requires closed source, paid software which is unavailable for most platforms. This feature is completely useless to everyone except Microsoft Windows users. I am not a maintainer of this project, so this is just my opinion, but I think forking splatnet2statink into a separate project would make more sense than trying to push such a huge update that will benefit only a small subset of users.

**Comment by ofiala-a51** [comment]
Huh, I didn't know Excel was an open standard as well... what you claim after that is not true though. This feature was not asked for. If it was, there would be at least one issue before your PRs ;)

**Comment by radsutton** [comment]
That's true. It's an open request in stat.ink. I think someone asked about it for this program somewhere, but I can't back that up. ;) but it's obviously something that people other than the 15 people in my group will use.

**Comment by frozenpandaman** [comment]
Hi! Like I mentioned in #105, I don't think I want to go ahead with any further feature development with this project, which is essentially in a complete state given the reasons I mentioned in that earlier PR; at this point I really do just want to make mandatory updates/fixes to keep it working, i.e. updating the headers to match the NSO app for continued functionality, and that's it. (This isn't really the point… but another issue I forgot to point out before is that it seems this is developed with Windows in mind but, for example, I develop on a Mac, and it's meant to be cross-platform as well – and I just don't have the ability or time to make sure everything works on all platforms, especially given the proposed flag does take paths… which can potentially have spaces in them, etc… many potentially compounding issues.)

I appreciate all the work you've put in here, and I do see the usefulness of a feature like this. As @ofiala-a51 pointed out, though, I haven't seen any other requests for this feature… and it doesn't seem you've created any issues/PRs on the [stat.ink repo](https://github.com/fetus-hina/stat.ink/issues) either? So not sure what you meant re: "It's an open request in stat.ink." Anyway, this should be taken into consideration too – I do think this is a relatively niche feature request for an already pretty-niche project.

Ultimately, this is an update adding advanced functionality that not all users need or want, and which would add two package requirements, which is in the end too much and definitely out-of-scope to merge with the main project's master branch here. I hope that makes sense! However, I agree with @ofiala-a51 – this is a *perfect* case for a fork of the project. I hope you maintain it for you + your team!

**Pull request closed without merging**
