### PR TITLE
Append --ignore-private flag

### PR DESCRIPTION
**Pull request by emaame**
Hello,
# I fixed and rearranged PR

It's not suitable to logging private matches for me.
because:
A) It's just for FUN with my friends.
B) I don't wanna record my friends' activities even if it's covered with dummy names.

So I append --ignore-private flags.
It may work, but it's still not tested well with the other flags.

p.s.
I think post_battle function interface is different between main and monitor_battles?
I don't touch it, just adding my option.

This is a great script!
Thanks.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Hi @emaame! Thanks for the suggestion and for the PR. I've also encountered wanting to not upload private battles, because they are often for fun or just fooling around, i.e. not actual battles where I (or others) are trying to perform well. 😁 However, the most common scenario for me is this:

1. Playing Splatoon (Turf/Ranked/League) using `-M mode`
2. Want to play private battles, so quit the script
3. Play private battles with friends, without splatnet2statink.py running
4. Start it again before playing more battles

In this situation, the option is not needed, as long as I am able to start/stop the script easily. The only case where I could see needing this option is as follows:

1. Playing Turf/Ranked/League battles, and forgot to run splatnet2statink.py
2. Play private battles with friends, and optionally Turf/Ranked/League after
3. Oh! I forgot to have the script running. Now I want to upload all past battles from today (including those from step 1), but not those in step 2 (private battles)

In this case I would just upload all to stat.ink and then manually delete the private ones from the server, but I recognize this is not an optimal solution. This would have been avoided had I remembered to run the script, but now the damage is done and I need a way through…

Or – I could maybe also see the option being needed if the script is running 24/7 on a Raspberry Pi or something (as at least one of our users has set up!) and they cannot stop/start it easily before and after they play Private Battles. (But again, there are times in which I *do* wish to record private battles, e.g. tournaments or when not just messing around).

Is this similar to your use case and your reasons for why you want to see this feature added, or could you let me know how you foresee using this? Thanks!

**Comment by emaame** [comment]
Thank you for your reply.

> I could maybe also see the option being needed if the script is running 24/7

Yes, It is!
I use a VPS server, and run this script as deamons with this option now (`-M` Is good).
I don't use connection from my iPhone to the VPS server,
So I need to wake up my PC to stop/start deamons. I'm lazy 😆 

Therefore I wanna switch disable/enable to send private matches with a CUI arguments.

> Is this similar to your use case and your reasons for why you want to see this feature added, or could you let me know how you foresee using this? Thanks! And glad you like the script!

I also hope its default is OFF.
But I don't wanna think about it works 24/7 automatically.
I did notice a last Splatoon2 update (maintenance) by an alive monitor script(it's also deamon) for this script!

best regards,
ema

**Comment by frozenpandaman** [comment]
@emaame,
Thanks! I never really thought of having it run constantly before, but now I understand this is a possible use of the script too. Of course, be careful to not try and fetch data too frequently… I fear Nintendo may not like that (making requests to their servers too frequently)… so, a high `-M` number is best. Here's a conversation I had about that with another user: https://twitter.com/frozenpandaman/status/935800823790972929

>I did notice a last Splatoon2 update (maintenance) by an alive monitor script(it's also deamon) for this script!

What do you mean? Another script that interfaces with this one, or…? (Sorry!)Also, what did running this script as a daemon produce when there was maintenance? I haven't tried that myself.

Anyway, this looks pretty good to me. I'll talk with @clovervidia and we'll accept this soon or follow up if there's anything else to discuss. 😄

このスクリプトのため助けてくれてありがとう！

**Comment by emaame** [comment]
> Anyway, this looks pretty good to me. I'll talk with @clovervidia and we'll accept this soon or follow up if there's anything else to discuss. 😄
> このスクリプトのため助けてくれてありがとう！

It's my pleasure!

> so, a high -M number is best. Here's a conversation I had about that with another user: https://twitter.com/frozenpandaman/status/935800823790972929

Sure! 50 matches may are required at least 50 mins even if they are ranked matches.
But I wanna check in stat.ink manually, so I use 900 as `-M` parameter (15 mins).
Now It's stable so I think more less frequency to fetch.

> What did running this script as a daemon produce when there was maintenance? I haven't tried that myself. I assume it just crashed after not being able to contact the Nintendo servers/URL?

I'm so sorry to confuse you.
I run another deamon to automatically restart splatnet2statink.py and tell by e-mail.
When the last maintenance, splatnet2statink.py was stopped and the report e-mail was arrived.
Then I noticed a maintenance.

 I'll write about it if I feel like it. Do not expect :p

**Comment by frozenpandaman** [comment]
Hey @emaame,

@clovervidia has expressed some concerns to me that this feature likely wouldn't be used by many people (only for a portion of those few running it as a daemon) and would make the launch options look even more complicated (even as is, could be hard to understand for some):
```
$ python splatnet2statink.py [-M [N]] [-r] [-s] [--ignore-private] [-t]
```
In addition, I think adding this could get a bit complicated coding-wise, as you pointed out in your original post, e.g. making sure `--ignore-private` can only be used with `-M` mode (or not?), how it works with `-r` in uploading missed/past recent battles, etc.

What's nice about open source like this is that hopefully you're able to add this feature/modification in your own fork and get use out of it, even if it's not included in the official version here. 😊 And it's not too many complicated changes so you should still be able to update easily, although I understand even that requires some maintenance on your end every update which isn't too ideal especially if running it as a daemon!

What would you think about a key/value you could add to your `config.txt` to disable private battles? e.g. adding the line
   ```
       "ignore_private": true
   ```
to the end of the JSON array, after the config file is generated on first run/setup. Then we could just easily check for the presence of this key in the `post_battle()` method itself, and if the battle type is private just return without uploading anything. I think this might be our best bet, and would set a good path for further adding other similar customizations/features in the future. What do you think?

Also, in response to your last comment,

>I run another deamon to automatically restart splatnet2statink.py and tell by e-mail. the report e-mail was arrived. I'll write about it if I feel like it. Do not expect :p

Would definitely love to know more about it or see the code or how it works, you ever have the chance and feel comfortable sharing! Very cool. :)

Thanks!

**Comment by emaame** [comment]
Thank you for your deeply concern.
My conclusion is agreement to your suggestion.
Since I have my own fork, I won't be in trouble w/o this change.

> What would you think about a key/value you could add to your config.txt to disable private battles? e.g. adding the line

I agree it's a cooler idea than my idea!
It should be config item, not be a launch option.

> EDIT: Started to implement this idea (very extensible for future customization which I think is cool!) via a new method and just calling custom_option_exists_and_true("ignore_private") before posting to stat.ink. And if it's true, and lobby == "private", we just pass instead of posting. :) Seems to me like this will be a good solution!

Booyah!! It sounds PRETTY NICE!.

> to the end of the JSON array, after the config file is generated on first run/setup. Then we could just easily check for the presence of this key in the post_battle() method itself, and if the battle type is private just return without uploading anything. I think this might be our best bet, and would set a good path for adding other similar customizations/features in the future. What do you think?

well, it's a difficult. I cannot answer it must be necessary...
e.g.

`
post_battles: {
    ranked: true,
    turf_war: true,
    private: false
}
`

Such a configuration wraps my idea, but it should be exist?


> making sure --ignore-private can only be used with -M mode (or not?)

In my usecase it is Yes.

> how it works with -r in uploading missed/past recent battles, etc.

You are right, it's ambitious.
(I hope to ignore missed/past battles)

regards

**Comment by frozenpandaman** [comment]
@emaame,

I've added the custom keys feature and the `ignore_private` key in v0.2.0, 828ea7e. Any private battles will be completely ignored, as if they didn't happen, i.e. no "new battle result detected" printout, and they won't be counted in the summary ("x wins and x losses this session").

I've made a docs page for the feature here: https://github.com/frozenpandaman/splatnet2statink/wiki/custom-keys

It also works in non-monitoring mode – if you try and upload a private battle with the key set to `true` in your `config.txt`, it will just print "Battle #i: skipping upload based on ignore_private key." I haven't explicitly tested it with `-r` but it should work just fine.

Please let me know how this works for you! I'll close this for now unless there are other issues. :)

**Comment by emaame** [comment]
Thank you for your help!
I try this.

**Comment by frozenpandaman** [comment]
See @emaame's guide here for running a daemon yourself: https://emaame.github.io/splatnet2statink_runs_as_daemon.en.html

Awesome!

**Pull request closed without merging**
