### PR TITLE
several small improvements

### PR DESCRIPTION
**Pull request by Tiryoh**
There are several small changes in this pull request.

* Add shebang to splatnet2statink.py
* Fix multi-byte char error
* Add license notation to splatnet2statink.py
* Add requirements.txt (for required Python libraries)

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Hi @Tiryoh,

Thanks for your PR. I'll respond to each commit in order:

1. We could add a shebang line, though we instruct all users (whether running the script on a Unix-based OS or not) to use `python splatnet2statink.py` at this point, which I think works fine for now. If we change to allow for execution via `./splatnet2statink.py`, we'd want to update the readme as well with instructions on how to `chmod +x` the file to allow for that. However, I think it's fine the way it currently is, and matches the readme too. If a user *needs* or for some reason really wants to run the file as an executable they should be able to easily add that line up top on their local copy. :)

2. @clovervidia seems to have added this in b09a7f9. However, I don't think multi-byte/non-Latin characters will be displayed to the user at any point, except for if `debug = True` which is only used for internal debugging purposes. Uploading to stat.ink and all user-facing printout is all fine at the moment, which is good.

3. I think we want to shy away from doing this. This is a simple project and truly doesn't *need* a license file, imo (or, it [doesn't really matter](https://opensource.stackexchange.com/a/2905) if it has one or not). I've talked with @clovervidia about this and he agrees as well. Despite this, we'll keep the GPLv3 since I agree with the philosophy of it (although probably relegate it just to the readme – I've done some reading and the license doesn't actually need to be included, just stated, to apply). Contributors are listed on GitHub so people can see who helped out, and what their contributions are, but adding someone into this list of copyright-holders for [adding a single comma](https://github.com/frozenpandaman/splatnet2statink/commits?author=mkody) is a bit excessive – and unnecessary – as is putting paragraphs of text in the top of the file, for whatever reason, really. And of course, as for all projects, copyrights are still present even without explicitly stating them. I think the copyright status/information/etc. and how it [currently applies](https://opensource.stackexchange.com/questions/2907/does-the-owner-of-the-github-repository-own-the-copyright-to-the-code) is fine, and people can feel free to send PRs, issues, feedback, or otherwise contribute as they see fit and/or desire.

4. Since there are only two requirements/packages to be installed, I think we'll just stick to having the user install them manually, not from a separate .txt file.

**Comment by Tiryoh** [comment]
Hello @frozenpandaman ,


Thanks for the reply.  
I think I understand your stance for splatnet2statink, it's very nice for everyone to make this repository simple! :D
I have several opinions and questions.

1. Why `splatnet2statink.py` does have execution authority which `dbs.py` and `iksm.py` do not have?  I thought this was for execution via `./splatnet2statink.py`.  (I don't think its a problem not to allow for execution via `./splatnet2statink.py` for now.)

2.  b09a7f9  was made after I made this PR, so there is no way for me to know that. :<  
Anyway, thanks for adding coding declaration.
This was the log for the multi-byte char error (tested on Windows10, repository ver 8923eec).  I should have created an issue for this, sorry for that.
    ```
    >python splatnet2statink.py -i データ20170906\results.json
      File "splatnet2statink.py", line 230
    SyntaxError: Non-ASCII character '\x83' in file splatnet2statink.py on line 230, but no encoding 
    declared; see http://python.org/dev/peps/pep-0263/ for details
    ```


3. OK!  
I found contributors name in line1 and 2, so I thought it stands for declaration for the copyright.  This was the only reason I added the license notation to main Python script, so please don’t worry about it too much.

4. OK!

**Comment by frozenpandaman** [comment]
@Tiryoh,

1. Are you talking about the `if __name__ == "__main__":` line? This is because the file is meant to be run from the CLI (`python splatnet2statink.py`), but the other files are not meant to be run in this way – they are just for declaring auxiliary functions, etc. with no output by themselves – and used to keep the `splatnet2statink.py` code cleaner and the file a bit shorter. I think we will add in the shebang line soon, but will want to update the readme at the same time to do any explanation that would go along with this change.

Actually, if you'd like to submit a PR for just that line (I don't know how to `cherry-pick`(?) a PR, or only accept/pull one of the commits from this one…) I'd be happy to accept it when I have a bit of time to update the readme with the instructions (in a few days).

2. No worries! It took me a while to reply to you as well. Thanks for the suggestion to add it, and I hope in doing so it fixed those problems for you. Of course, let me know if you are still running into any errors. It can be annoying to account for how filesystems often have trouble with certain filenames (non-Latin characters, spaces…)

3. No problem, and thanks for explaining. :) We were just trying to list the creators/main authors of the project (contributed the majority of the code, design, etc.) Of course, other contributors can be found on the GitHub page – and we're very glad that some of our users have wanted to help out, provide bugfixes, etc.!

**Comment by Tiryoh** [comment]
@frozenpandaman ,

> Are you talking about the if __name__ == "__main__": line? 

Sorry for not explaining enough.  I'm talking about the file permission.
As I run `ls -la`, I can find that `splatnet2statink.py` has execution authority.
I guess this means someone has run `chmod +x splatnet2statink.py` and pushed to this reposotory.

```
$ ls -la
total 168
drwxrwxr-x  13 tiryoh  tiryoh    442  9  8 16:58 .
drwxr-xr-x  41 tiryoh  tiryoh   1394  9  8 16:29 ..
drwxrwxr-x  17 tiryoh  tiryoh    578  9  8 16:58 .git
-rw-r--r--   1 tiryoh  tiryoh     16  9  8 00:03 .gitignore
-rw-r--r--   1 tiryoh  tiryoh      7  9  7 01:33 .python-version
-rw-r--r--   1 tiryoh  tiryoh   3646  9  8 16:58 README.md
-rw-r--r--   1 tiryoh  tiryoh    486  9  7 01:33 config.txt
-rw-r--r--   1 tiryoh  tiryoh  11289  9  7 01:33 dbs.py
-rw-r--r--   1 tiryoh  tiryoh  10630  9  7 14:26 dbs.pyc
-rw-r--r--   1 tiryoh  tiryoh   7229  9  7 01:33 iksm.py
-rw-r--r--   1 tiryoh  tiryoh   6563  9  7 14:26 iksm.pyc
drwxrwxr-x  11 tiryoh  tiryoh    374  9  7 01:33 sample_jsons
-rwxr-xr-x   1 tiryoh  tiryoh  26775  9  8 16:58 splatnet2statink.py
```

**Comment by frozenpandaman** [comment]
@Tiryoh,

Ahh, I see. :) Good to know it's already executable; I was able to run it fine using the `./splatnet2statink.py` syntax on my machine as well. However, I think if someone clicks the green button to download the repo from the GitHub project page, instead of `git clone`ing it, the file permissions may be reset to default (so, cannot execute).

I'll accept #13 shortly, once I update the readme and have more time to test it myself, along with fixing another security check issue.

**Comment by Tiryoh** [comment]
@frozenpandaman,

Thanks!

**Pull request closed without merging**
