### PR TITLE
Update App Version to 1.9.0

### PR DESCRIPTION
**Pull request by rinsuki**
This pull request fix following error.

```
splatnet2statink v1.5.5
The stored cookie has expired.
Attempting to generate new cookie...
Error from Nintendo (in Account/Login step):
{
  "status": 9427,
  "correlationId": "xxxxxxxx-xxxxxxxx",
  "errorMessage": "Upgrade required."
}
```

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Thanks, appreciated! Can you bump the version number to 1.5.6 as well?

**Comment by rinsuki** [comment]
Done!

**Comment by frozenpandaman** [comment]
I'll update the binary/executable version of this for Mac tomorrow. @tkgstrator any chance you could make one for Windows again? 😅 If not, no worries, just thought I should ask in case (glad I remembered!)

**Comment by tkgstrator** [comment]
Done.

https://github.com/tkgstrator/splatnet2statink/releases/tag/v1.5.6

**Comment by frozenpandaman** [comment]
Thank you!! 🙏🙏

**Pull request merged**
