### PR TITLE
Version updates

### PR DESCRIPTION
**Pull request by Jetsurf**
Quick changes I made during testing of the 1.4.1 -> 1.5.0.1 update.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
The [Play Store page](https://play.google.com/store/apps/details?id=com.nintendo.znca&hl=en_US) for the app lists 1.5.0 as the current version. Is the header currently being sent in the Android version of the app (if you mitm it) actually 1.5.0.1, and this just doesn't show on the store page for some reason, or...?

**Comment by Jetsurf** [comment]
Ah, I MITM'ed my iPhone which reports the following user agent:

`com.nintendo.znca/1.5.0.1 (iOS/12.3)`

I don't test on Android, but thought the versions would match up.

**Comment by frozenpandaman** [comment]
There's been cases where they haven't in the past, where the iTunes/App Store version gets a minor update & version change that the Play Store variant doesn't (i.e. likely an iOS-specific bugfix or change). Weird because the [App Store page](https://itunes.apple.com/us/app/nintendo-switch-online/id1234806557) also just lists the version as 1.5.0, not 1.5.0.1.

s2s follows the Android app header format, so I'll check to see what it is tonight and let you know if changes are needed here before approving the PR.

**Comment by frozenpandaman** [comment]
The Android version is using `1.5.0` in the headers. Could you update your PR @Jetsurf?

image

image

**Comment by Jetsurf** [comment]
Yep! One second.

**Pull request merged**
