### PR TITLE
Package as a Python module

### PR DESCRIPTION
**Pull request by ticky**
Hi there, really enjoying your work on this script! I just spent an afternoon [packaging it up to run quietly in the background on Heroku](https://github.com/ticky/splatnet2statink-heroku), but I had a little bit of trouble. Mostly, this is because Heroku’s weird, but the best workaround I could find was to install this natively with Python’s own installation tools, so this PR is a proposal to add that!

I’m not someone who works on Python all the time, so this might not be perfect, but what this accomplishes is:

1. The package can be installed by `pip install -e git+https://github.com/frozenpandaman/splatnet2statink.git#egg=splatnet2statink`
1. If you wanted to, you could publish this to [PyPI](https://pypi.org) and it could then be installed with *just* `pip install splatnet2statink`!
1. The program can be run as just `splatnet2statink` on the command-line, from any folder!

I tried my best not to mess with too much, but I had to move the code into a folder so it counted as a “module, and the stuff that was previously in the `if __name__ == "__main__":` block had to go into `main` itself. That meant it could be called from the command-line stub `pip` will create. It still functions the same, whether called directly or as `splatnet2statink`!

I haven’t updated the readme yet, I wanted to run this by you and see if you were up for the change!

You can try this out yourself by checking out this version of the code, and using `pip install -e git+https://github.com/ticky/splatnet2statink.git#egg=splatnet2statink `. You should then end up with a `splatnet2statink` command you can run, and it should pick up your configuration from your current working directory, and work as usual.

### CODE REVIEW

**Comment by ticky** [comment]
A friend has tested for me and 83acd4618e380d3be0870e30bd12e62f07cefbda fixes the issue! I don’t see any other instances where global variables were used and not annotated remaining.

**Comment by ticky** [comment]
Just rebased this atop current master.

**Comment by ticky** [comment]
The other issue I’ve noticed with this is that the auto-updater doesn’t work correctly. It wrongly presumes `dbs.py` will be in the current directory.

**Comment by clovervidia** [comment]
I was wondering about how updates would work with the project as a module. Would it still be possible to update via git like how it works right now when installed with pip? Also, moving the `dbs.py` will have some consequences for non-git users of older versions as the update script checks the readme from the repo to find the version number before downloading the latest `dbs.py` from its current location as the URL is hardcoded in the script, so it would need to be replicated in both directories.

**Comment by frozenpandaman** [comment]
Sorry I hadn't gotten around to responding to this yet @ticky. Thanks for your work and support!

I think something like this is possible, but also I'm not sure if it's a direction we (or I) want to take the project in directly. At least in the start, I intended for this to be a simple/lightweight, single-file, local Python script you can run to upload your battles. I think pip integration could be cool in theory, and I do want to allow users who are hoping to run this [automatically](https://github.com/frozenpandaman/splatnet2statink/wiki/automation) (on Heroku or whatever) to be able to find a setup that's best for them, but also I don't really want this to be a "package" (or a separate PyPI site along with this one) or some command you can just run whenever on the command line (even though it would still need a config file in the current directory, so either way you're navigating somewhere that contains this file before you launch it) – I sort of want it to just be a normal Python script.

I'm also aiming for it to be dead-easy to use and as accessible as possible, especially for people who aren't familiar with the CLI or anything (unlike most GitHub projects, I feel) and thus am sort of wary of there being any sort of "installation" or files being auto-magically being moved to hidden/special directories like /usr/local/bin and added to my path or whatnot. When I (or anyone) manually and simply deletes the folder, they should be able to remove all traces of it, just like that, cf. "executable" philosophy vs. "installer." The same is true for Docker support (cc #36, @hasegaw) – any number of these sorts of things are possible and cool to maintain in forks, but it complicates things a bit (conceptually and in practice) and are maybe a bit out of scope for this repo, in my mind.

**Comment by ticky** [comment]
> but also I don't really want this to be a "package" (or a separate PyPI site along with this one)

This certainly doesn’t _mandate_ using PyPI; it would work from a GitHub URL too. It just means installation can actually become automated, with the standard tools for using Python code, which also made it possible for implementation on Heroku to actually package the program as part of the bundle.

> it would still need a config file in the current directory, so either way you're navigating somewhere that contains this file before you launch it

That was something I was hoping to address at a later point, but yeah, a fair cop.

Regarding updating, I was going to look into making the mechanism a bit smarter; it appears that the self-updater doesn’t actually reload the updated `dbs.py` at all right now, instead relying on it being loaded in the next invocation. I was also going to make it possible for that file to be stored in the current directory even with the pip version.

All that being said, given you’re not interested in this approach, I’ve now updated my Heroku implementation to comply. It now instead caches the code of the program alongside the configuration.

**Pull request closed without merging**
