### PR TITLE
update headers for NSO app v1.10.1

### PR DESCRIPTION
**Pull request by niyari**

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Thank you for staying so on top of this, always! 

@tkgstrator Let me know if you could provide a Windows build, but no rush 😊

**Comment by frozenpandaman** [comment]
Hiya @tkgstrator, hoping it's OK to ping you again about this, if you'd be able – no worries if not, just let me know!

**Comment by nkizz** [comment]
Enclosed is a windows build!
[splatnet2statink.zip](https://github.com/frozenpandaman/splatnet2statink/files/6135032/splatnet2statink.zip)

**Comment by frozenpandaman** [comment]
@nkizz You are awesome, thanks so much!

**Comment by tkgstrator** [comment]
@nikzz Thank you so much!

**Pull request merged**
