### PR TITLE
avoid using nickname for sort if s_flag

### PR DESCRIPTION
**Pull request by nu50218**
First of all, thank you for nice script!

When s_flag is true, another team member's nickname is set to None while my nickname is set to string.
That's why in this battle (https://stat.ink/@nu50218/spl2/3675280) this error was caused.

```
Traceback (most recent call last):
  File "/splatnet2statink/splatnet2statink.py", line 1282, in <module>
    populate_battles(is_s, is_t, is_r, debug)
  File "/splatnet2statink/splatnet2statink.py", line 375, in populate_battles
    post_battle(0, [result], s_flag, t_flag, -1, True if i == 0 else False, debug, False)
  File "/splatnet2statink/splatnet2statink.py", line 1092, in post_battle
    payload = set_scoreboard(payload, bn, mystats, s_flag)
  File "/splatnet2statink/splatnet2statink.py", line 658, in set_scoreboard
    sorted_ally_scoreboard = sorted(ally_scoreboard, key=itemgetter(0, 1, 3, 4, 2, 11), reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Awesome, thank you for catching & fixing this @nu50218!

**Comment by frozenpandaman** [comment]
@nkizz @tkgstrator Please let me know if one of you would be available to build this release for Windows (thanks, again, as always!)

**Comment by nkizz** [comment]
Sure thing, right now I’m on the road away from my desktop, but I’ll be
able to run one later this week😄

**Comment by frozenpandaman** [comment]
@nkizz Just a ping on the above, if/when you have a chance!

**Comment by tkgstrator** [comment]
@frozenpandaman Don't you try to build the release for Windows with GitHub Actions?

**Comment by frozenpandaman** [comment]
@tkgstrator Not quite sure how to do that. 🙃

I guess [this](https://github.com/marketplace/actions/pyinstaller-windows) would be the one I want but not exactly sure how to set it up, and seems to be a little out of date…

**Comment by nkizz** [comment]
Totally slipped my mind, thanks for the ping. Keep up the great work!
[splatnet2statink.zip](https://github.com/frozenpandaman/splatnet2statink/files/6430881/splatnet2statink.zip)

**Comment by frozenpandaman** [comment]
You're awesome, will get it up on the page tonight, thanks!

**Pull request merged**
