### PR TITLE
update headers for NSO app v1.10.0

### PR DESCRIPTION
**Pull request by niyari**

### CODE REVIEW

**Comment by frozenpandaman** [comment]
thanks!! :) could you bump it to v1.5.6 so users will get prompted for an update?

**Comment by issei-m** [comment]
@frozenpandaman Could you release this version on GitHub? I maintain the docker image for this that is automated its build relying on this repository's release tag.
I don't hurry, so anytime fine.

**Comment by frozenpandaman** [comment]
@issei-m Ah, sure – spaced out about this one, hah, sorry! Thanks for the reminder (and thank you for your work, too!)

I just updated the Mac version on the [Releases page](https://github.com/frozenpandaman/splatnet2statink/releases). @tkgstrator could you possibly do this for the Windows one yet again? Thank you if so!! :)

**Comment by tkgstrator** [comment]
Yes, I'll build it for Windows in this week.

**Comment by frozenpandaman** [comment]
Thank you so much!! :) So appreciated!

**Comment by tkgstrator** [comment]
Sorry keep you waiting. I've done.

https://github.com/tkgstrator/splatnet2statink/releases/tag/v1.5.7

**Comment by frozenpandaman** [comment]
Thank you so much!! Got it! :)

**Pull request merged**
