### PR TITLE
update headers for NSO app v1.12.0

### PR DESCRIPTION
**Pull request by niyari**
It looks like these can be made into common variables.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
@niyari Good point! Do you want to make that change now? If so, feel free and then I'll merge the PR. :)

I'm traveling until the 10th and can update the new executable builds (and make sure everything is working there) then.

**Comment by frozenpandaman** [comment]
ping on this when you have a chance @niyari!

**Comment by niyari** [comment]
What do you think?🙇
https://github.com/niyari/splatnet2statink/commit/8a1e7512931b110315dca853716562ec7b48c2ba

**Comment by frozenpandaman** [comment]
Sorry for the delay @niyari, looks good! Can you modify the PR to merge in the patch-1 branch instead of master? (or, push this commit to your master branch so I can merge it?

**Comment by issei-m** [comment]
@frozenpandaman Can you release it?

**Comment by frozenpandaman** [comment]
Whoops! Forgot all about that, heh…

Thank you @issei-m, done!

**Comment by issei-m** [comment]
Thank you :)

**Pull request merged**
