### PR TITLE
Add shebang to main script

### PR DESCRIPTION
**Pull request by Tiryoh**
Arrangement to allow for running via `./splatnet2statink.py`
https://github.com/frozenpandaman/splatnet2statink/pull/11#issuecomment-328015194
https://github.com/frozenpandaman/splatnet2statink/pull/11#issuecomment-328031977

### CODE REVIEW

**Comment by Tiryoh** [comment]
@frozenpandaman,

This is an additional information.
I get the following error to run main Python script on my ubuntu server by `./splatnet2statink.py` on current version( 579d5f9 ).

```
$ ./splatnet2statink.py
import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
import.im6: unable to open X server `' @ error/import.c/ImportImageCommand/368.
from: can't read /var/mail/io
from: can't read /var/mail/operator
./splatnet2statink.py: 11: ./splatnet2statink.py: A_VERSION: not found
Warning: unknown mime-type for "splatnet2statink v" -- using "application/octet-stream"
Warning: unknown mime-type for "+" -- using "application/octet-stream"
Warning: unknown mime-type for "A_VERSION" -- using "application/octet-stream"
Error: no such file "splatnet2statink v"
Error: no such file "+"
Error: no such file "A_VERSION"
./splatnet2statink.py: 15: ./splatnet2statink.py: try:: not found
./splatnet2statink.py: 16: ./splatnet2statink.py: Syntax error: "(" unexpected
```

**Comment by frozenpandaman** [comment]
Thanks for the info @Tiryoh. I received a similar error when testing on a Ubuntu server. This can be fixed by adding the shebang to *all* .py files (so, to `dbs.py` and `iksm.py` as well). Feel free to amend your PR to include this, or I can add it myself just as easily when I merge this PR in a day or two (after I have a chance to update the readme and work out another security issue, as I mentioned before).

**Comment by Tiryoh** [comment]
@frozenpandaman,
I didn't need to add shebang to `dbs.py` and `iksm.py` (only to `splatoon2statink.py`), but do you wish to add shebang to them?

**Comment by frozenpandaman** [comment]
@Tiryoh, It runs fine on macOS with the shebang only in `splatoon2statink.py` for me, but when testing on an Ubuntu server (shared server, used for web hosting) it was giving me that error until I added the line in all three, strangely. Though you are right, it *should* work/only be required by the main file that will be executed, and not in the others (as they are only imported). So I'll look into this as well. I think we're fine just adding it to the main file for now, so no worries. :)

**Comment by Tiryoh** [comment]
OK, I understand the situation!

**Comment by frozenpandaman** [comment]
Hm, seemed to work on my Unix environment this time with only the shebang in the main script, so that's good.
Merged, and updated the readme with a note about `chmod +x` in e0dc084. Thanks again @Tiryoh! Please let me know if you have any problems.

**Comment by Tiryoh** [comment]
@frozenpandaman,
It worked fine on my environment, too.
Thank you so much for the update!

**Pull request merged**
