### PR TITLE
update iksm.py

### PR DESCRIPTION
**Pull request by tkgstrator**
Nintendo changed some headers value for NSO update.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Glad it was an easy fix! Thanks so much!

@tkgstrator, could you bump the version number to 1.5.5? Then I'll merge this. :)

**Comment by tkgstrator** [comment]
Done.

**Comment by frozenpandaman** [comment]
I no longer have access to a Windows machine to build the [pre-compiled executable](https://github.com/frozenpandaman/splatnet2statink/releases) for v1.5.5. If you do, could you help me out and build it for me, by chance?

All this involves is installing [PyInstaller](https://www.pyinstaller.org/) via pip, and then running the command `pyinstaller --onefile --icon=s2s.ico splatnet2statink.py`. (ICO file [here](https://elifessler.com/splatoon/s2s.ico))

If you're on Windows and could do this, and send me the resulting .exe to host on the repo's releases page, that'd be great!

**Comment by tkgstrator** [comment]
I've done, here :)

https://github.com/tkgstrator/splatnet2statink/releases/tag/1.5.5

P.S
Executable file is little larger than yours lol.

**Comment by frozenpandaman** [comment]
Thank you so much, really appreciated!

And hah, no worries (hmm, I wonder why it can vary so much?) – the Mac one is always even larger. :)

**Comment by tkgstrator** [comment]
First time, I thought pyinstaller tried to include all of libraries installed on my computer. So I created virtual environment using anaconda and build it again but did not change. Hmm, I'm curious.

**Comment by frozenpandaman** [comment]
I am too! Interesting. But no big deal at all. :D

**Pull request merged**
