### PR TITLE
Automatically build for Windows release with GitHub Actions

### PR DESCRIPTION
**Pull request by tkgstrator**
Add actions.yaml for GitHub Actions can build the Windows release with latest Pyinstaller.

### CODE REVIEW

**Comment by frozenpandaman** [comment]
@tkgstrator Hey, do you know how to fix this? I merged this in right before #122 hoping it'd run, but nothing had showed up in the repo's [Actions](https://github.com/frozenpandaman/splatnet2statink/actions) tab even after waiting a while… so I manually created a release… which then caused it to run, as it noticed the tag had been created… but then it failed to update the existing release (I think it needs [allowUpdates](https://github.com/marketplace/actions/create-release)?) So I deleted the `v1.5.11` tag/release and tried re-running the job and now it's just stuck in "Status: Queued," tied to the `v1.5.11` tag which no longer exists. I eventually cancelled the run, and deleted the workflow run/log.

It seems I can't run it manually unless it's [configured with the `workflow_dispatch` event](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) – is this what you'd recommend? Thanks – sorry, this is all new to me!

Also, a few other notes:

1. I noticed you added the `.ico` file but the .yaml action [doesn't use](https://github.com/tkgstrator/splatnet2statink/blob/74b85a00c3ed6b2f11d9de6cdd54080595c98615/.github/workflows/actions.yaml#L25) it anywhere, i.e. does not include the flag `--icon=s2s.ico`
2. Is there any way to get the resulting zip to be named `splatnet2statink-v{x.x.x}-Windows.zip` instead of just `splatnet2statink-Windows.zip`?

**Comment by tkgstrator** [comment]
GitHub Actions written in this PR is enabled to create a release page automatically when you make a tag having prefix `v` (like `v1.10.1`). If owner already have done. GitHub Actions always failed as you thought. 

I think there might be some options of `overwrite` or `force update`, but I have known currently. 

> I think just clicking a button to run it manually might be best/easiest for me.

 Okay, I'll find the way you want.

> since I will be building the Mac version myself and have to add it manually

How to build the release for Mac? GitHub Actions unlimited supported to build on Mac if a repository is public. If you want I am updating the PR to apply for macOS.

> 1. I noticed you added the .ico file but the .yaml action doesn't use it anywhere, i.e. does not include the flag --icon=s2s.ico

I forgot to add the option `--icon=s2s.ico`!
 
> 2. Is there any way to get the resulting zip to be named splatnet2statink-v{x.x.x}-Windows.zip instead of just splatnet2statink-Windows.zip?

Yes.

Sincerely.

**Comment by frozenpandaman** [comment]
Thanks so much! So helpful & kind of you. 🙂 

>create a release page automatically when you make a tag having prefix v (like `v1.10.1`).

Ah, now I see that, cool! I created a tag via the GitHub site, and I didn't upload any binaries to it – according to [this answer](https://stackoverflow.com/a/28500451/3580553) that should make a tag without making a release? – but it still failed. Is the action not trying to create the new tag, and then failing?

>Okay, I'll find the way you want.

Actually I'm fine with this, as long as I understand it, I think. 😅 I could see it working one two ways:
1. I make the tag (a release with no binaries) manually, and then it uploads the binaries.
2. I make the tag, then click "run action," and it uploads the binaries.
Either way is OK with me! But I think in either case "allowing updates" is for the best.

> How to build the release for Mac? [...] If you want I am updating the PR to apply for macOS.

Sure, this would be great! I use the same command on Mac as on Windows:
```
pyinstaller --onefile --icon=s2s.ico splatnet2statink.py
```
The .ico bit doesn't actually _work_ on Mac, for what it's worth, but I don't mind. :)

Thanks again so much for all your help + support!

**Comment by frozenpandaman** [comment]
Aha!! Nevermind on the building front, I found that I can actually manually download the successful build from the "Arficacts" section under the workflow run details. So I'll upload the .zip!

**Pull request merged**
